# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('hotscore', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_url', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('query_word', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
