# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180628_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
