# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproduct',
            name='query_word',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
