# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0002_featureproduct_query_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproduct',
            name='goodreads_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
